title: Ria Sachdeva
logo: assets/images/Untitled design-6.png
description: Email id - ria.sachdeva2000@gmail.com
<a href= "www.linkedin.com/in/riasachdeva">👔 LinkedIn</a> 
show_downloads: False
theme: jekyll-theme-minimal
