title: Ria Sachdeva
logo: assets/images/Untitled design-6.png
description: 
   Data analyst with biotechnology background with experience in statitiscal modelling, machine learning and data visualisation through R, SQL and Python.
  <br><br>
  <a href="https://www.linkedin.com/in/riasachdeva/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
    <br><br>
#show_downloads: False
theme: jekyll-theme-minimal
